### ISSUE TITLE
RevSlice requires repr(C) or repr(transparent)

### ISSUE THREAD

**Issue by dtolnay** [scottmcm/rev_slice#1]
Without one of those attributes, my understanding is the transmute from &[T] to &RevSlice\<T\> is undefined behavior. The compiler is free to stick some additional data at the start of RevSlice\<T\> or give it a stricter alignment than [T]. For example some targets may require all struct types to have some minimum alignment that is not required for slices.

From nomicon's [*Alternative representations*](https://doc.rust-lang.org/nomicon/other-reprs.html):

> `#[repr(C)]` is also necessary to soundly do more elaborate tricks with data layout such as reinterpreting values as a different type.

**Comment by scottmcm** [comment]
Yes, that's theoretically true right now, but it may very soon not be: https://github.com/rust-rfcs/unsafe-code-guidelines/pull/31#issuecomment-426730654

**Comment by scottmcm** [comment]
Made it transparent in 0.1.4.

https://github.com/scottmcm/rev_slice/blob/b555bcdbbac762df26eda690833a567fcbf6767d/src/lib.rs#L65-L68
